[appendix]
[[_apx_coding-standards]]
= Coding Standards


[NOTE]
----
TODO: include content of https://incodehq.atlassian.net/wiki/display/EST/Incode+Coding+Convention+Convention
... and there are probably several more
----


== Value Types

* use `XxxType.Meta` to gather together constants for datatypes (eg names, codes, descriptions etc).



== Entities

* Do specify `@Persistent(schema=..., table=...)
** schema will probably be `dbo`, unless only connected using polymorphic association (table of two halves) pattern
* Do specify `@DomainObject(objectType="...")`
** for new entities, use "schema.table" as the value
* If in an inheritance hierarchy `@Discrimininator("...")
** for new entities, use "schema.table" as the value


* for injected services, use: `@NotPersistable @Inject` +
+
The `@NotPersistable` means that the field isn't part of the QXxx entity, thus simplify the writing of type-safe queries.



== Repositories

* test repository queries using integration tests (not unit tests)
* are typesafe queries used rather than JDOQL?

== Behaviour

* mixins... see EST-1559


== Layout/Cosmetics

* use `@MemberOrder` to associate actions with properties or collections
* use `.layout.xml` for other layouts.
** each layout should have a General/Application level/Metadata tab
* follow conventional prefixes for action names, to automatically pick up CSS icons (hard-coded in `EstatioAppManifest`, search for "isis.reflector.facet.cssClassFa.patterns")


== Preferred style

* streams rather than guava `FluentIterable` +
+
[WARNING]
====
if the collection is DN-managed (eg `Order#items`), then wrap in an `ArrayList`.

So, rather than:

[source,java]
----
getItems()
    .stream()
    .map(...)
----

write:

[source,java]
----
Lists.newArrayList(getItems())
    .stream()
    .map(...)
----

====




== Deprecated (to remove)

** replace deprecated Apache Isis annotations and domain services
** have any `injectXxx()` and `setXxx()` been replaced by `@Inject`
** has AssertJ been used rather than Hamcrest
** replace JDOQL with typesafe queries


