[appendix]
[[_apx_coding-standards]]
= Coding Standards


[NOTE]
----
TODO: include content of https://incodehq.atlassian.net/wiki/display/EST/Incode+Coding+Convention+Convention
... and there are probably several more
----


== Value Types

* use `XxxType.Meta` to gather together constants for datatypes (eg names, codes, descriptions etc).



== Entities

* Do specify `@Persistent(schema=..., table=...)
** schema will probably be `dbo`, unless only connected using polymorphic association (table of two halves) pattern
* Do specify `@DomainObject(objectType="...")`
** for new entities, use "schema.table" as the value
* If in an inheritance hierarchy `@Discrimininator("...")
** for new entities, use "schema.table" as the value
* Do specify `@XmlJavaTypeAdapter(PersistentEntityAdapter.class)`


* for injected services, use: +
+
[source,java]
----
@Inject
@NotPersistable
SomeService someService;
----
+
The `@NotPersistable` means that the field isn't part of the QXxx entity, thus simplify the writing of type-safe queries.


== View Models (JAXB)

* for injected services, use: +
+
[source,java]
----
@Inject
@XmlTransient
@Getter(AccessLevel.NONE)
@Setter(AccessLevel.NONE) +
SomeService someService;
----


== Repositories

* test repository queries using integration tests (not unit tests)
* are typesafe queries used rather than JDOQL?



== Mixins

(per EST-1559)

Six reasons for mixins:

1. decoupling across domain modules .. ie contribute behaviour to dependent.  eg Party_invoicesFrom

2. decoupling across layers ... ie allow app layer functionality be accessible from domain layer; eg. Property_fixDisplayOrder

3. reuse of behaviour in mixin's inheritance hierarchy.  For example, DomainObject_triggerAbstract.

4. for separation of concerns, a la DCI.  Thus helper methods live on the mixin rather than on the underlying entity, and only inject services into the mixin as required.

5. Less error prone?  Standardisation of "act", "prop" or "coll" as method names, with the member's name being derived from mixin class.

6. Lets cross-cutting functionality that might apply to several different classes be brought together, even though it isn't necessarily decoupled from all of those classes.  For example, "_sync".

~~~
For the Estatio codebase, I think the prevailing sentiment is:

- (1) is fine as a reason to use mixins
- (2) ... ok ?
- (3) .. case-by-case; depends on how much functionality is in the superclass
- (4) ... no
- (5) ... no
- (6) ... ok ?



== Layout/Cosmetics

* use `@MemberOrder` to associate actions with properties or collections
* use `.layout.xml` for other layouts.
** each layout should have a General/Application level/Metadata tab
* follow conventional prefixes for action names, to automatically pick up CSS icons (hard-coded in `EstatioAppManifest`, search for "isis.reflector.facet.cssClassFa.patterns")


== Preferred style

* streams rather than guava `FluentIterable` +
+
[WARNING]
====
if the collection is DN-managed (eg `Order#items`), then wrap in an `ArrayList`.

So, rather than:

[source,java]
----
getItems()
    .stream()
    .map(...)
----

write:

[source,java]
----
Lists.newArrayList(getItems())
    .stream()
    .map(...)
----

====




== Deprecated (to remove)

** replace deprecated Apache Isis annotations and domain services
** have any `injectXxx()` and `setXxx()` been replaced by `@Inject`
** has AssertJ been used rather than Hamcrest
** replace JDOQL with typesafe queries


