[appendix]
[[_apx_design-standards]]
= Design Standards




== Architecture/Layering

* separate out menu from repository, with the menus in `estatio-app`

== Class Responsibilities

* use mixins rather than contribution services
* use actions vs property edits appropriately
** don't have actions called "change" or "edit"; search instead for the deeper business rule
** actions used for business modifications with side-effects
** simple property edits used when no side-effects?




== Commit message format

Use the format:

[source,]
----
EST-xxxx: fixes the yada yada yada
----

that is, specifying the Jira issue number, and then a description of the change in the _present_ tense.

[TIP]
====
The idea of using present tense is that the commit history, when read back, can be read as: "this patch, if it is applied... "
====

For example: 

* `EST-864: fixes bad reference to country-dom (was -SNAPSHOT, should be 1.13.0)`
* `EST-863 and EST-865: moves base and documentation module out to incode.`
* `EST-861: removes EstatioUserRole, with functionality moved to EstatioRole`





== Editing Asciidoc

Some guidance on writing Asciidoc (this list will likely grow in the future):

* Start each sentence in a paragraph on a new line. +
+
This makes it easy to spot too-long sentences, and sentences that are repetitive. +
It also makes it easy to apply pull requests to documentation.
