[appendix]
[[_design-coding-standards]]
== Design/Coding Standards



=== Code/Implementation

[NOTE]
----
TODO: include content of https://incodehq.atlassian.net/wiki/display/EST/Incode+Coding+Convention+Convention
... and there are probably several more
----


=== Architecture/Layering

* separate out menu from repository, with the menus in `estatio-app`

=== Class Responsibilities

* use mixins rather than contribution services
* use actions vs property edits appropriately
** don't have actions called "change" or "edit"; search instead for the deeper business rule
** actions used for business modifications with side-effects
** simple property edits used when no side-effects?
* use `XxxType.Meta` to gather together constants for datatypes (eg names, codes, descriptions etc).

[NOTE]
----
??? should we deprecate regular actions and use mixins everywhere ???
----

=== Entities

* Do specify `@Persistent(schema=..., table=...)
** schema will probably be `dbo`, unless only connected using polymorphic association (table of two halves) pattern
* Do specify `@DomainObject(objectType="...")`
** for new entities, use "schema.table" as the value
* If in an inheritance hierarchy `@Discrimininator("...")
** for new entities, use "schema.table" as the value

=== Repositories

* test repository queries using integration tests (not unit tests)
* are typesafe queries used rather than JDOQL?

=== Layout/Cosmetics

* use `@MemberOrder` to associate actions with properties or collections
* use `.layout.xml` for other layouts.
** each layout should have a General/Application level/Metadata tab
* follow conventional prefixes for action names, to automatically pick up CSS icons (hard-coded in `EstatioAppManifest`, search for "isis.reflector.facet.cssClassFa.patterns")

=== Remove Deprecated Features

** replace deprecated Apache Isis annotations and domain services
** have any `injectXxx()` and `setXxx()` been replaced by `@Inject`
** has AssertJ been used rather than Hamcrest
** replace JDOQL with typesafe queries





=== Commit message format

Use the format:

[source,]
----
EST-xxxx: fixes the yada yada yada
----

that is, specifying the Jira issue number, and then a description of the change in the _present_ tense.

[TIP]
====
The idea of using present tense is that the commit history, when read back, can be read as: "this patch, if it is applied... "
====

For example: 

* `EST-864: fixes bad reference to country-dom (was -SNAPSHOT, should be 1.13.0)`
* `EST-863 and EST-865: moves base and documentation module out to incode.`
* `EST-861: removes EstatioUserRole, with functionality moved to EstatioRole`





=== Editing Asciidoc

Some guidance on writing Asciidoc (this list will likely grow in the future):

* Start each sentence in a paragraph on a new line. +
+
This makes it easy to spot too-long sentences, and sentences that are repetitive. +
It also makes it easy to apply pull requests to documentation.
